### ISSUE TITLE
No log

### ISSUE THREAD

**Issue by eliassjogreen** [manyuanrong/deno-plugin-prepare#1]
Provide an easy way (function or flag) to turn off logging and or redirect it.

**Comment by manyuanrong** [comment]
Because downloading binary files is very slow in some cases, people don't know what happened. If you do not want to output logs, you can refer to https://deno.land/std/log/README.md to adjust the log level or the log handler.

```ts
import * as log from "https://deno.land/std@v0.35.0/log/mod.ts";
await log.setup({
    loggers:{
        default: { level: "ERROR", handlers: [] }
    }
})
```

**Comment by eliassjogreen** [comment]
Ok, guss I'll close the issue then

**Comment by eliassjogreen** [comment]
Your solution does not work due to the https://github.com/manyuanrong/deno-plugin-prepare/blob/209079d281e19e28e12cbbd2589425dc623b1685/mod.ts#L9 that disposes all existing handlers. To solve this you simply need to remove it.
