### ISSUE TITLE
use deno 1.0.0 got error

### ISSUE THREAD

**Issue by yeukfei02** [manyuanrong/deno-plugin-prepare#15]
```
error: TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.6.0/mod.ts:64:15
```

After I run `deno cache myfile.ts`
`Deno.openPlugin` does not exist in 1.0.0?

**Comment by manyuanrong** [comment]
The plugin API is currently not stable, so you need to use the --unstable flag, please make sure to use deno run --unstable xx.ts

**Comment by yeukfei02** [comment]
@manyuanrong i already add `--unstable` flag
