### ISSUE TITLE
Updating plugin to match the release/module version

### ISSUE THREAD

**Issue by eliassjogreen** [manyuanrong/deno-plugin-prepare#2]
Right now the plugin-prepare only downloads the new version if the local path of the plugin is changed. This however is not very good in cases where you would want to update the plugin using a new github release. It would therefor be preferred if for example it in the .deno_plugins directory kept a file for which release version (or checksum) that is currently downloaded. Hopefully this is just a temporary solution until [#4222](https://github.com/denoland/deno/issues/4222) is resolved and there is no need for this module.

**Comment by manyuanrong** [comment]
Multi-version coexistence is now supported, especially if many libraries cross depend on different versions
https://github.com/manyuanrong/deno-plugin-prepare/releases/tag/v0.2.0
