### ISSUE TITLE
Support local files

### ISSUE THREAD

**Issue by eliassjogreen** [manyuanrong/deno-plugin-prepare#3]
It's me again. I would love support for locally built files for using `deno-plugin-prepare` in development but because `fetch` doesn't support local fetching of files it throws the following:
```
error: Uncaught TypeError: scheme 'file' not supported
```

**Comment by manyuanrong** [comment]
I don't think there is a problem supporting local files, but it doesn't seem to make much sense. This is just convenient for debugging during development。

I think what you want is this. It will be more convenient
https://github.com/manyuanrong/deno_mongo/blob/master/build.ts

**Comment by eliassjogreen** [comment]
Although that build script wouldn't work anymore now that there is multi-file support because of the checksum part of the filename. I could use the checksum for the release url but that just seems like a lot of work each time you release a new version.
